### ISSUE TITLE
Set up correct database permissions

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/trusted_checksum_repository#10]
https://docs.google.com/document/d/18MPHfUtEwNrCp2idmSt-TvDnxF3P0Kt3WWWnN5pBZ7M/edit#heading=h.yzqsqntox27w

The API should connect to the Postgres database with a user than also only has Create and Read permissions on the underlying database.

**Comment by tallenaz** [comment]
From TCR Requirements doc: (https://docs.google.com/document/d/18MPHfUtEwNrCp2idmSt-TvDnxF3P0Kt3WWWnN5pBZ7M/edit#) 

"The TCR API only handles CREATE and READ actions against the database, not Update or Delete. This is to prevent malicious manipulation of the TCR by a compromised system." 

and 

"To accommodate deletion and other administrative actions, we'll create a method that is not exposed via the API AND requires the (admin) user to log onto the production machine and run the (Rails) method via the Rails console. This way we're not exposing a back door via web services while still avoiding manual SQL querying." 

db level permissions restricting updates and deletes shouldn't be necessary if the http API only exposes methods that CREATE and READ. AFAIK the console user connects as the db user, and so will need db level permissions to carry out the unexposed actions.
