### ISSUE TITLE
(TCR, R) what is required for  TCR to store zipped checksums

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/trusted_checksum_repository#23]
Determine what is required to make TCR viable as the storage location for MD5 for zipped versions to be replicated.

Story Time Notes: https://docs.google.com/document/d/10HMhTMWlZaM1DJChFr2r3coOVDZKe0EDAH8PPumb-2E/edit#

**Comment by ndushay** [comment]
What is needed for viability:
### VMs
- [ ] stage VM (`sul-tcr-dev.stanford.edu`)
    - [ ] follows naming conventions
    - [x] box for rails app (ruby, passenger ...)
    - [x] db works
    - [ ] pres_cat stage can send ReST GET/POST/PATCH
- [ ] prod VM (`checksum-repository-prod.stanford.edu`)
    - [ ] follows naming conventions
    - [x] box for rails app (ruby, passenger ...)
    - [x] db works
    - [ ] log rotation
    - [ ] certs (?)
    - [ ] pres_cat prod can send ReST GET/POST/PATCH
### TCR code
- [x] db schema accommodating checksum(md5) storage associated with druid, version
- [ ] db model as needed for zipped druid/version checksum(s)
    - [ ] AR validation for checksums (e.g. number of chars, regex) w specs (1 hour)
- [ ] controller allowing zipped version checksum POST and GET
    - [ ] specs for controller (2 hours)
    - [ ] copes with POST when it already exists (doesn't blow up)
    - [ ] (JSON) response for GET
- [x] routes for zipped version checksum POST/GET
- [ ] README (1 hour)
- [ ] shared_configs if nec (2 hours)
    - [ ] use config gem, set up settings.yml
    - [ ] create branches in shared_configs repo
    - [ ] update cap recipes to link to settings.yml and update shared_configs repo
- [ ] working deploy scripts
    - [ ] stage VM
        - [ ] change to _stage_  (< 1 hour)
        - [x] works to _dev_ VM
    - [x] prod VM
- [ ] honeybadger hookup (< 1 hour)
- [ ] okcomputer landing page (2 hours)
- [ ] nagios checks (2 hours)
- [ ] devops docs
    - [ ] to production checklist (1 hour)
    - [ ] operations concerns (1 hour)

**Comment by ndushay** [comment]
I estimate about 2-3 days of heads down contact hours.

**Comment by tallenaz** [comment]
Spinning up 2 vanilla rails machines will take one day, tops. Getting certs once requested takes one business day, usually.

**Comment by ndushay** [comment]
@julianmorley See above for very thorough list of all the small tasks required to get TCR ready for md5 for zipped files.   Many tasks, but none are big -- and usually, said lists aren't as thorough as this.  :-)

I would say TCR is a viable place for MD5 checksums, but it's not my call.

**Comment by ndushay** [comment]
I am closing this ticket, as we won't be storing MD5 for zipped moab versions in TCR.
